
spring:
  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.29:3306/front_crossshop?useUnicode=true&allowMultiQueries=true&useSSL=false
    username: test
    password: root@123


server:
  port: 448
  ssl:
    key-store-type: JKS
    key-store: tomcat.keystore
    enabled: true
    key-store-password: 147258369
    key-alias: tomcat

